import os
from dotenv import load_dotenv

from azure.ai.evaluation import GroundednessEvaluator # uses openai deployment for groundedness
from azure.identity import DefaultAzureCredential
from agent_framework import ai_function

load_dotenv()

@ai_function
def check_agent_groundedness(
    agent_response: str,
    source_docs: list[str],
    query: str = "",
) -> dict:
    """
    Check if agent response is grounded in source documents using Azure AI Content Safety.
    Groundedness scores range from 1 to 5, with 1 being the least grounded.
    and 5 being the most grounded. Default threshold in GroundednessEvaluator is 3.

    Args:
        agent_response: The response generated by the agent
        source_docs: List of source document texts to validate against
        query: Original query/question (optional but recommended)
    
    Returns:
        dict: {"is_grounded": bool, "grounding_score": float, "reason": str}
    """
    # Use Azure AI Project endpoint (simpler config)
    azure_ai_project = os.getenv("AZURE_AI_PROJECT_ENDPOINT")
    if not azure_ai_project:
        raise ValueError("AZURE_AI_PROJECT_ENDPOINT env variable must be set!")
    

    model_config = {
        "azure_endpoint": os.getenv("AZURE_OPENAI_ENDPOINT"),
        "azure_deployment": "gpt-4.1",
    }

    # Initialize evaluator with managed identity
    evaluator = GroundednessEvaluator(
        model_config=model_config,
        threshold=3,
        credential=DefaultAzureCredential(),
    )
    
    # Combine source docs into context
    context = "\n\n".join(source_docs)
    
    # Run groundedness check
    result = evaluator(
        query=query,
        response=agent_response,
        context=context,
    )

    # Parse result:
    # groundedness_result: True: pass, False: fail,
    # groundedness_score: from 1 ungrounded to 5 completely grounded,
    # and groundedness_reason: explanation string for the score
    return {
      "groundedness_result": result.get("groundedness_result", False),
      "groundedness_score": result.get("groundedness", 0),
      "groundedness_reason": result.get("groundedness_reason", "")
    }



######################################
## Example usage for local testing ##
######################################

if __name__ == "__main__":
    import json
    
    # Test grounded response
    response = check_agent_groundedness(
        query="When was Marie Curie born?",
        agent_response="Marie Curie was born in Warsaw in 1867.",
        source_docs=["Marie Curie was born on November 7, 1867 in Warsaw."]
    )

    print(json.dumps(response, indent=4))

    # Test clearly ungrounded response (different person entirely)
    response = check_agent_groundedness(
        query="When was Albert Einstein born?",
        agent_response="Albert Einstein was born in Germany in 1879 and developed the theory of relativity.",
        source_docs=["Marie Curie was born on November 7, 1867, in Warsaw, Poland."]
    )

    print(json.dumps(response, indent=4))