"""
Fact Checker Agent Module
-------------------------
This module defines a Fact Checker agent that verifies the GROUNDEDNESS
of responses generated by other agents using Azure AI Content Safety.
"""

from agents.base import chat_client
from agent_framework import ChatAgent

from safety.groundedness_check import check_agent_groundedness

# TODO: Define the Fact Checker agent that uses the groundedness check function
...

